# Generated by Django 5.0.2 on 2024-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_backend', '0002_alter_item_available_stock_alter_item_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.CharField(max_length=100),
        ),
    ]
