# Generated by Django 5.0.2 on 2024-02-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_backend', '0004_alter_item_available_stock_alter_item_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
