# Generated by Django 5.0.2 on 2024-02-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaizntree_backend', '0005_alter_item_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_stock',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock_status',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
